<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/31 0031
 * Time: 上午 10:10
 */

namespace app\admin\controller;


use cmf\controller\AdminBaseController;
use app\portal\model\PortalCategoryModel;
use tree\Tree;
use app\admin\model\RouteModel;
use app\portal\model\PortalPostModel;
class ChildrenController extends AdminBaseController
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->parentId = 21;
    }

    /*
     * 儿童学院编辑
     */
    public function edit()
    {
        $id = $this->parentId;
        if ($id > 0) {
            $category = PortalCategoryModel::get($id)->toArray();
            $portalCategoryModel = new PortalCategoryModel();
            $where = ['delete_time' => 0,'path'=>['Like','0-'.$this->parentId.'%']];
            $categories = $portalCategoryModel->order("list_order ASC")->where($where)->select()->toArray();
            $tree       = new Tree();
            $tree->icon = ['&nbsp;&nbsp;│', '&nbsp;&nbsp;├─', '&nbsp;&nbsp;└─'];
            $tree->nbsp = '&nbsp;&nbsp;';

            $newCategories = [];
            foreach ($categories as $item) {
                $item['selected'] = $category['parent_id'] == $item['id'] ? "selected" : "";
                array_push($newCategories, $item);
            }
            $routeModel = new RouteModel();
            $alias      = $routeModel->getUrl('', ['id' => $id]);

            $category['alias'] = $alias;
            $tree->init($newCategories);
            $str     = '<option value=\"{$id}\" {$selected}>{$spacer}{$name}</option>';
            $treeStr = $tree->getTree(0, $str);

            $this->assign($category);
            $this->assign('categories_tree', $treeStr);
            $this->assign('parentId', $this->parentId);
            return $this->fetch();
        } else {
            $this->error('操作错误!');
        }
    }

    /*
     * 儿童学院编辑保存
     */
    public function editPost()
    {
        $data = $this->request->param();

        $result = $this->validate($data, 'PortalCategory');

        if ($result !== true) {
            $this->error($result);
        }

        $portalCategoryModel = new PortalCategoryModel();

        $result = $portalCategoryModel->editCategory($data);

        if ($result === false) {
            $this->error('保存失败!');
        }

        $this->success('保存成功!');
    }
}