<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/11 0011
 * Time: 上午 11:45
 */

namespace app\wap\controller;


use cmf\controller\HomeBaseController;
use app\portal\model\PortalCategoryModel;
use tree\Tree;
use app\admin\model\RouteModel;
use app\portal\model\PortalPostModel;
use app\admin\model\BannerModel;
class LiveController extends HomeBaseController
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->parentId = 16;
    }
    /*
     * 文章列表
     */
    public function index()
    {
        $param = $this->request->param();

        $categoryId = $this->request->param('cid', $this->parentId, 'intval');
        $portalPostModel = new PortalPostModel();

        $where = [
            'a.create_time' => ['>=', 0],
            'a.delete_time' => 0
        ];

        $join = [
            ['__USER__ u', 'a.user_id = u.id']
        ];

        $field = 'a.*,u.user_login,u.user_nickname,u.user_email';

        if (!empty($categoryId)) {
            $where['b.category_id'] = ['eq', $categoryId];
            array_push($join, [
                '__PORTAL_CATEGORY_POST__ b', 'a.id = b.post_id'
            ]);
            $field = 'a.*,b.id AS post_category_id,b.list_order,b.category_id,u.user_login,u.user_nickname,u.user_email';
        }

        $startTime = empty($param['start_time']) ? 0 : strtotime($param['start_time']);
        $endTime   = empty($param['end_time']) ? 0 : strtotime($param['end_time']);
        if (!empty($startTime) && !empty($endTime)) {
            $where['a.published_time'] = [['>= time', $startTime], ['<= time', $endTime]];
        } else {
            if (!empty($startTime)) {
                $where['a.published_time'] = ['>= time', $startTime];
            }
            if (!empty($endTime)) {
                $where['a.published_time'] = ['<= time', $endTime];
            }
        }

        $keyword = empty($param['keyword']) ? '' : $param['keyword'];
        if (!empty($keyword)) {
            $where['a.post_title'] = ['like', "%$keyword%"];
        }

        $where['a.post_type'] = 1;
        $where['a.post_status'] = 1;

        $articles        = $portalPostModel->alias('a')->field($field)
            ->join($join)
            ->where($where)
            ->order('update_time', 'DESC')
            ->paginate(8);
        $articles->appends($param);

        $Banner = new BannerModel();
        $banner = $Banner->where(['type'=>'live'])->find();
        $this->assign('banner',$banner);
        $this->assign('articles', $articles->toArray());
        $this->assign('category', $categoryId);
        $this->assign('page', $articles->render());
//var_dump($articles->toArray());exit;
        return $this->fetch();
    }
}